name: LatentColor
channels:
  - nvidia/label/cuda-11.8.0
  - nvidia
  - https://repo.anaconda.com/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2024.11.26
  - cuda-cccl=12.4.127
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=11.8.89
  - cuda-nvcc=11.8.89
  - cudatoolkit=11.8.0
  - ld_impl_linux-64=2.40
  - libcublas=12.4.5.8
  - libcublas-dev=11.11.3.6
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.4.1.48
  - libcusparse=12.3.1.170
  - libcusparse-dev=11.7.5.86
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.10.15
  - readline=8.2
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - accelerate==1.2.0
      - addict==2.4.0
      - ailut==1.5.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.18
      - aiosignal==1.3.2
      - albucore==0.0.24
      - albumentations==2.0.8
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - argparse==1.4.0
      - async-timeout==5.0.1
      - attrs==24.2.0
      - automat==24.8.1
      - av==14.1.0
      - bilateral-slicing==0.0.0
      - buildtools==1.0.6
      - cachetools==5.5.2
      - calflops==0.3.2
      - causal-conv1d==1.0.0
      - certifi==2024.8.30
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.0
      - click==8.1.8
      - cloudpickle==3.1.0
      - codecov==2.1.13
      - colorama==0.4.6
      - coloredlogs==15.0.1
      - constantly==23.10.4
      - contourpy==1.3.1
      - coverage==7.6.12
      - crcmod==1.7
      - cryptography==44.0.1
      - cycler==0.12.1
      - dists-pytorch==0.1
      - docopt==0.6.2
      - dominate==2.7.0
      - einops==0.8.0
      - exceptiongroup==1.2.2
      - facexlib==0.3.0
      - faster-coco-eval==1.6.5
      - filelock==3.14.0
      - filterpy==1.4.5
      - flake8==7.1.2
      - flatbuffers==25.2.10
      - fonttools==4.55.1
      - frozenlist==1.6.0
      - fsspec==2024.10.0
      - furl==2.1.3
      - fvcore==0.1.5.post20221221
      - google-auth==2.38.0
      - google-auth-oauthlib==0.4.6
      - greenlet==3.1.1
      - grpcio==1.68.1
      - h5py==3.12.1
      - huggingface-hub==0.26.3
      - humanfriendly==10.0
      - hyperlink==21.0.0
      - idna==3.10
      - imageio==2.36.1
      - incremental==24.7.2
      - iniconfig==2.0.0
      - interrogate==1.7.0
      - iopath==0.1.10
      - isort==5.10.1
      - jinja2==3.1.4
      - jmespath==0.10.0
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - kiwisolver==1.4.7
      - kmeans-pytorch==0.3
      - kornia==0.8.0
      - kornia-rs==0.1.8
      - lazy-loader==0.4
      - lightning-utilities==0.14.3
      - llvmlite==0.44.0
      - lmdb==1.6.2
      - lpips==0.1.4
      - lut-transform==0.0.0
      - mamba-ssm==1.0.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.3
      - mccabe==0.7.0
      - mdurl==0.1.2
      - medpy==0.5.2
      - ml-collections==1.0.0
      - mmcv-full==1.7.2
      - mmengine==0.10.6
      - model-index==0.1.11
      - mpmath==1.3.0
      - multidict==6.4.3
      - networkx==3.4.2
      - ninja==1.11.1
      - numba==0.61.0
      - numpy==1.24.2
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - onnxruntime==1.20.1
      - opencv-python==4.7.0.72
      - opencv-python-headless==4.12.0.88
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openxlab==0.1.2
      - ordered-set==4.1.0
      - orderedmultidict==1.0.1
      - oss2==2.17.0
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.0.0
      - platformdirs==4.3.6
      - plotly==5.24.1
      - pluggy==1.5.0
      - portalocker==3.0.0
      - propcache==0.3.1
      - protobuf==3.19.6
      - psutil==6.1.0
      - py==1.11.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycodestyle==2.12.1
      - pycparser==2.22
      - pycryptodome==3.21.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pyflakes==3.2.0
      - pygments==2.19.1
      - pyparsing==3.2.0
      - pytest==8.3.4
      - pytest-runner==6.0.1
      - python-dateutil==2.9.0.post0
      - pytorch-fid==0.3.0
      - pytorch-lightning==2.5.1.post0
      - pytz==2023.4
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - redo==3.0.0
      - regex==2024.11.6
      - requests==2.28.2
      - requests-oauthlib==2.0.0
      - rich==13.4.2
      - rsa==4.9
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - seaborn==0.13.2
      - selective-scan==0.0.2
      - seplut-ext==1.2.0
      - setuptools==75.8.0
      - simpleitk==2.4.0
      - simplejson==3.19.3
      - simsimd==6.5.0
      - six==1.16.0
      - sqlalchemy==2.0.36
      - stringzilla==3.12.6
      - submitit==1.5.2
      - sympy==1.13.3
      - tabulate==0.9.0
      - tenacity==9.0.0
      - tensorboard==2.10.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.2.2
      - termcolor==2.5.0
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tifffile==2024.9.20
      - timm==0.4.12
      - tokenizers==0.20.3
      - tomli==2.2.1
      - torch==2.2.0
      - torchaudio==2.2.0+cu118
      - torchmetrics==1.7.1
      - torchsummary==1.5.1
      - torchvision==0.17.0+cu118
      - tornado==6.4.2
      - tqdm==4.65.2
      - transformers==4.46.3
      - triton==2.2.0
      - twisted==24.11.0
      - typing-extensions==4.12.2
      - typing-inspection==0.4.1
      - tzdata==2024.2
      - urllib3==1.26.20
      - visdom==0.2.4
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - yacs==0.1.8
      - yapf==0.43.0
      - yarl==1.20.0
      - zope-interface==7.2
prefix: /data/anaconda3/envs/LatentColor
